### ISSUE TITLE
Is this fork still maintained?

### ISSUE THREAD

**Issue by pfarrell** [Netbreeze-GmbH/boilerpipe#4]
I am working on a command line utility to help with execution of boilerpipe in a pipeline as well as creating a web api (likely a separate project).  I was going to upload my own fork of 2.2.0 from the [subversion repo](https://code.google.com/p/boilerpipe/) however, if this project is alive and well, I'd rather work off/with others than just drop another fork.

Is this fork/project still maintained?

**Comment by brndkfr** [comment]
Hello Patrick,
we implemented some small improvements that we needed therefore we forked. At the moment there is no ongoing development and maintenance. So feel free to fork from here.

**Comment by pfarrell** [comment]
Bernd,

Thanks for the quick reply. If I make anything cool in it, I'll let you know.
