### ISSUE TITLE
Can't find version 1.2.2

### ISSUE THREAD

**Issue by falmanna** [Netbreeze-GmbH/boilerpipe#5]
I am trying to include version 1.2.2 in my project, but it seems that maven is not able to find it!
I am able to find version 1.1.0, which doesn't have MediaExtractor.
do I need to add another repository than maven?

**Comment by cmeury** [comment]
This is a fork of the original boilerplate code and was never uploaded to Maven Central as far as I recall. You would have to clone and `mvn install` the project to get it into your local repository or upload it to your maven cache if you have one (Artifactory, Nexus, etc.).

**Comment by firasalmanna** [comment]
Actually, there is version 1.1.0 in maven.
Anyway, I found two other forks of the version 1.2.2 uploaded to maven, 
one is 'com.robbypond.boilerpipe'
the other is 'com.syncthemall.boilerpipe'

thanks.

**Comment by cmeury** [comment]
@firasalmanna Yes, my answer was a bit unclear maybe. I meant that only this fork was never uploaded to Maven Central. Hope you'll make it work, otherwise just comment here again :)

**Comment by firasalmanna** [comment]
No problem :)
Both versions I mentioned up are working like a charm!
Thank you.
